Some changes in webconfig and Security Controller on Security folder,…
MontanchezJuan/UrbanNav_Backend pull request #7
Opened 2023-10-25 14:40 UTC by SilvaG45

vechicles class created on Bussines folder

2023-10-25 14:46 UTC, NicolasCastilloGaleano approved these changes

2023-10-25 17:14 UTC, MontanchezJuan requested changes
Santiago, I suggest you to add update and destroy methods

2023-10-31 12:11 UTC, MontanchezJuan approved these changes

2023-10-31 12:23 UTC, mahz24 approved these changes

2023-11-01 19:46 UTC, NicolasCastilloGaleano approved these changes

2023-11-02 01:40 UTC, merged